name: CI


on:
 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

 
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: self-hosted

   
    steps:
      
      - uses: actions/checkout@v3

      
      - name: compile java project
        run: javac HelloWorld.java
      - name: run java project
        run: java HelloWorld
